version: "2"

linters:
  settings:
    custom:
      logcheck:
        path: logcheck.so
        settings:
          check-lowercase: true
          check-english: true
          check-special: true
          check-sensitive: true
          sensitive-words:
            - username
            - email
