version: "2"

linters:
  defalt: none
  enable:
    - logcheck

  settings:
    custom:
      logcheck:
        path: logcheck.so

        settings:
          check-lowercase: true
          check-english: false
          check-special: false
          check-sensitive: false

          sensitive-words:
            - username
            - email
